name: Deploy to Azure Web App
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # (optional) quick sanity that deps resolve
      - name: Validate deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy (Oryx build on runner)
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-britedge-44194
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          enable-oryx-build: true
